# Site settings
title: 芥为之舟
header-img: "img/twitter.jpg"
tagline: "cn"  
description: "fzsens|獨步天下，吾心自潔，無念無執，如林中之象"  
baseurl: ""
url: "http://qiongsong.com"  

# About/contact
owner: 
  name: "fzsens"
  email: fzsens@gmail.com
  bio: "林中之象"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

github_username: fzsens
weibo_username: 傅琼松
zhihu_username: fu-qiong-song

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
kramdown:
  input: GFM
  auto_ids: true
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "fzsens"
      header-img: "img/twitter.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus
  duoshuo :
    short_name : 
  disqus :
      short_name : qiongsong

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
